name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v5   # Pages 메타데이터 준비
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'
      - run: npm ci
      - name: Build for Pages
        env:
          BASE_PATH: /woongtest1234/      # 레포명과 일치!
        run: npm run build
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist                    # 빌드 산출물 폴더
  deploy:
    needs: build
    runs-on: macos-14
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4