name: CI (macOS)

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ feature/** ]

jobs:
  test_and_build:
    runs-on: macos-14   # macOS GitHub-hosted runner
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Install
        run: npm ci

      - name: Test
        run: npm run test

      - name: Build (no deploy here)
        env:
          # PR/feature 브랜치 빌드 시는 base를 루트로 둡니다
          BASE_PATH: /
        run: npm run build
